### ISSUE TITLE
TypeError: Cannot read property 'contours' of undefined

### ISSUE THREAD

**Issue by Wildhoney** [ecomfe/gulp-fontmin#2]
When I specify the `text` option &ndash; and specifically the **i** character, I receive:

> TypeError: Cannot read property 'contours' of undefined at /Users/atimberlake/Webroot/Mobile/node_modules/gulp-fontmin/node_modules/fontmin/node_modules/fonteditor-ttf/lib/ttf/table/OS2.js:175:59

``` javascript
var alphaNumeric = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefgh';

return gulp.src('public/fonts/pt-sans-web/**.ttf')
           .pipe(fontmin({ text: alphaNumeric }))
           .pipe(gulp.dest('public/fonts'));
```

That above runs fine, but as soon as I append **i** to the end of `alphaNumeric` then the error is raised.

The font file I'm trying to minify is this one: https://www.dropbox.com/s/gv3yv4nnp8jigdk/PTS75F_W.ttf?dl=0

**Comment by junmer** [comment]
@Wildhoney thanks for your issue
please update to `0.7.2` to have a try

**Comment by Wildhoney** [comment]
Thanks @junmer &ndash; could you please `npm publish` `0.7.2`?

**Comment by junmer** [comment]
@Wildhoney :sweat_smile:  pubed , thx

**Comment by Wildhoney** [comment]
Much better! Thank you @junmer :+1:
