### ISSUE TITLE
option `quiet: true` ignored in gulp-fontmin

### ISSUE THREAD

**Issue by matthewnessworthy** [ecomfe/gulp-fontmin#5]
Your plugin has come in really handy, however I have found a small bug, description below:

At https://github.com/ecomfe/gulp-fontmin/blob/master/index.js#L139 there's an option to trigger the callback prior to outputting any messages. 

There appears to be a missing return statement which is allowing the plugin to call the callback twice as well as output messages.

**Comment by jamesjryan** [comment]
I'm having the same, passing {quiet: true} is ignored.
